name: Build and Deploy Worker

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@latest

      - name: Set up Node.js
        uses: actions/setup-node@latest
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Build project
        run: |
          npx wrangler deploy --dry-run --outdir=dist
          cp ./dist/worker.js ./_worker.js

      - name: Commit and push built worker
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _worker.js
          git commit -m "Automated build: update _worker.js"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
